---
- hosts: dev
  become: True
  tasks:
    - name: start the container
      docker_container:
        name: tomcat
        image: "balaji504/tomcat:1.0"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
